# Generated by Django 5.0.6 on 2025-03-26 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Injury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "injury_type",
                    models.CharField(
                        choices=[
                            ("strain", "Strain"),
                            ("tear", "Tear"),
                            ("cramp", "Cramp"),
                            ("sprain", "Sprain"),
                            ("dislocation", "Dislocation"),
                            ("fracture", "Fracture"),
                            ("stress_fracture", "Stress Fracture"),
                            ("tendonitis", "Tendonitis"),
                            ("ligament_tear", "Ligament Tear"),
                            ("concussion", "Concussion"),
                            ("whiplash", "Whiplash"),
                            ("shin_splint", "Shin Splint"),
                            ("tennis_elbow", "Tennis Elbow"),
                            ("pinched_nerve", "Pinched Nerve"),
                            ("sciatica", "Sciatica"),
                            ("abrasion", "Abrasion"),
                            ("blister", "Blister"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "other_injury",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "recovery_time",
                    models.CharField(
                        choices=[
                            ("less_than_week", "Less than a week"),
                            ("couple_weeks", "Couple of weeks"),
                            ("one_month", "One Month"),
                            ("couple_months", "Couple of Months"),
                            ("years", "Years"),
                        ],
                        max_length=20,
                    ),
                ),
                ("treatment_taken", models.BooleanField(default=False)),
                (
                    "medical_report",
                    models.FileField(
                        blank=True, null=True, upload_to="medical_reports/"
                    ),
                ),
                (
                    "treatment_types",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "treatment_effectiveness",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("date_logged", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
