# Generated by Django 5.0.6 on 2025-03-29 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("InjurySupport", "0004_delete_treatment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SymptomLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        choices=[
                            ("head", "Head"),
                            ("neck", "Neck"),
                            ("shoulder", "Shoulder"),
                            ("arm", "Arm"),
                            ("elbow", "Elbow"),
                            ("wrist", "Wrist"),
                            ("hand", "Hand"),
                            ("chest", "Chest"),
                            ("back", "Back"),
                            ("stomach", "Stomach"),
                            ("hip", "Hip"),
                            ("leg", "Leg"),
                            ("knee", "Knee"),
                            ("ankle", "Ankle"),
                            ("foot", "Foot"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pain_level",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ]
                    ),
                ),
                (
                    "discomfort_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ache", "Ache"),
                            ("sharp_pain", "Sharp Pain"),
                            ("throbbing", "Throbbing"),
                            ("burning", "Burning"),
                            ("stiffness", "Stiffness"),
                            ("numbness", "Numbness"),
                            ("tingling", "Tingling"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "possible_cause",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("training", "Training"),
                            ("accident", "Accident"),
                            ("posture", "Posture"),
                            ("unknown", "Unknown"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("other_details", models.TextField(blank=True, null=True)),
                ("date_logged", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
