# Generated by Django 5.0.6 on 2025-03-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("InjurySupport", "0006_restandrecovery"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="restandrecovery",
            unique_together=set(),
        ),
    ]
