# Generated by Django 5.0.6 on 2025-04-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("InjurySupport", "0007_alter_restandrecovery_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="restandrecovery",
            name="recovering_from",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
